name: Continuous Integration

# trigger action on push or pull-request to master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    container: markus2101/mbdl-dev:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make build-script executable
      run: chmod +x scripts/build_native.sh

    - name: Build
      run: scripts/build_native.sh

    - name: Make clang-tidy script executable
      run: chmod +x scripts/run_clang_tidy.sh

    - name: Run clang-tidy analyzer
      run: scripts/run_clang_tidy.sh

    - name: Make unittests script executable
      run: chmod +x scripts/run_unittests.sh

    - name: Run unittests
      run: scripts/run_unittests.sh
