name: Continuous Integration

# trigger action on push or pull-request to master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    # checkout repository
    - name: Checkout
      uses: actions/checkout@v2

    # use our docker container
    - name: Build
      uses: ./.github/actions/
