name: Continuous Integration

# trigger action on push or pull-request to master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    # checkout repository
    - name: Checkout
    - uses: actions/checkout@v2

    # use our docker container
    - name: Docker
      uses: .ci/
      run: $GITHUB_WORKSPACE/scripts/build_native.sh
