name: Continuous Integration

# trigger action on push or pull-request to master branch
on:
  push:
    branches: [ master, improvement/move_dev_image_to_DockerHub ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    container: markus2101/mbdl-dev:latest

    steps:
    # checkout repository
    - uses: actions/checkout@v2
      with:
        ref: improvement/move_dev_image_to_DockerHub
    - name: Build
      run: scripts/build_native.sh
